name: Pushed To Main
on:
  push:
    branches:
      - 'main'
    paths:
      - 'kubernetes/cluster/qdrantcluster.yaml'
      - 'kubernetes/cluster-debug/qdrantcluster.yaml'
      - 'kubernetes/cluster-three/qdrantcluster.yaml'


jobs:
  check-and-apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for changes in cluster
        id: cluster_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^kubernetes/cluster/qdrantcluster.yaml$'; then
            echo "cluster_changed=true" >> $GITHUB_ENV
          else
            echo "cluster_changed=false" >> $GITHUB_ENV
          fi

      - name: Check for changes in cluster debug
        id: cluster_debug_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^kubernetes/cluster-debug/qdrantcluster.yaml$'; then
            echo "cluster_debug_changed=true" >> $GITHUB_ENV
          else
            echo "cluster_debug_changed=false" >> $GITHUB_ENV
          fi

      - name: Check for changes in cluster three
        id: cluster_three_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q '^kubernetes/cluster-three/qdrantcluster.yaml$'; then
            echo "cluster_three_changed=true" >> $GITHUB_ENV
          else
            echo "cluster_three_changed=false" >> $GITHUB_ENV
          fi

      - name: Apply Cluster
        if: env.cluster_changed == 'true'
        run: |
          echo "kubernetes/cluster/qdrantcluster.yaml"

      - name: Apply Cluster Debug
        if: env.cluster_debug_changed == 'true'
        run: |
          echo "kubernetes/cluster-debug/qdrantcluster.yaml"

      - name: Apply Cluster Three
        if: env.cluster_three_changed == 'true'
        run: |
          echo "kubectl apply -f kubernetes/cluster-three/qdrantcluster.yaml"
